---
http_interactions:
- request:
    method: post
    uri: https://test.slack.com/
    body:
      encoding: UTF-8
      string: payload={"attachments":[{"color":"#f00"}]}
    headers: {}
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/html; charset=utf-8
      Date:
      - Mon, 24 Mar 2014 15:42:47 GMT
      Server:
      - Apache
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        CTwhRE9DVFlQRSBodG1sPgo8aHRtbCBsYW5nPSJlbiI+CiAgPGhlYWQ+Cjxu
        b3NjcmlwdD48bWV0YSBodHRwLWVxdWl2PSJyZWZyZXNoIiBjb250ZW50PSIw
        OyBVUkw9Lz9ub2pzbW9kZT0xIiAvPjwvbm9zY3JpcHQ+CjxzY3JpcHQgdHlw
        ZT0idGV4dC9qYXZhc2NyaXB0Ij4KaWYoc2VsZiE9PXRvcCl3aW5kb3cuZG9j
        dW1lbnQud3JpdGUoIlx1MDAzQ3N0eWxlPmJvZHkgKiB7ZGlzcGxheTpub25l
        ICFpbXBvcnRhbnQ7fVx1MDAzQ1wvc3R5bGU+XHUwMDNDYSBocmVmPVwiI1wi
        IG9uY2xpY2s9IisKIlwidG9wLmxvY2F0aW9uLmhyZWY9d2luZG93LmxvY2F0
        aW9uLmhyZWZcIiBzdHlsZT1cImRpc3BsYXk6YmxvY2sgIWltcG9ydGFudDtw
        YWRkaW5nOjEwcHhcIj5HbyB0byBTbGFjay5jb21cdTAwM0NcL2E+Iik7Cjwv
        c2NyaXB0Pgo8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+CgoKdmFy
        IFRTX2xhc3RfbG9nX2RhdGUgPSBudWxsOwp2YXIgVFNNYWtlTG9nRGF0ZSA9
        IGZ1bmN0aW9uKCkgewoJdmFyIGRhdGUgPSBuZXcgRGF0ZSgpOwoJCgl2YXIg
        eSA9IGRhdGUuZ2V0RnVsbFllYXIoKTsKCXZhciBtbyA9IGRhdGUuZ2V0TW9u
        dGgoKSsxOwoJdmFyIGQgPSBkYXRlLmdldERhdGUoKTsKCgl2YXIgaCA9IGRh
        dGUuZ2V0SG91cnMoKTsKCXZhciBtaSA9IGRhdGUuZ2V0TWludXRlcygpOwoJ
        dmFyIHMgPSBkYXRlLmdldFNlY29uZHMoKTsKCXZhciBtcyA9IGRhdGUuZ2V0
        TWlsbGlzZWNvbmRzKCk7Cgl2YXIgc3RyID0geSsnLycrbW8rJy8nK2QrJyAn
        K2grJzonK21pKyc6JytzKycuJyttczsKCWlmIChUU19sYXN0X2xvZ19kYXRl
        KSB7CgkJdmFyIGRpZmYgPSBkYXRlLVRTX2xhc3RfbG9nX2RhdGU7CgkJLy9z
        dHIrPSAnICgnK2RpZmYrJ21zKSc7Cgl9CglUU19sYXN0X2xvZ19kYXRlID0g
        ZGF0ZTsKCXJldHVybiBzdHIrJyAnOwp9Cgp2YXIgVFNTU0IgPSB7CgljYWxs
        Q0VGMzogZnVuY3Rpb24obWV0aG9kLCBvYmpfYXJncywgaGFuZGxlcikgewoJ
        CXZhciB1cmwgPSAnaHR0cHM6Ly9zbGFja2NlZjMuY29tLycrbWV0aG9kOwoJ
        CQoJCWhhbmRsZXIgPSBoYW5kbGVyIHx8IGZ1bmN0aW9uKG9iKSB7fQoJCQoJ
        CXZhciByZXEgPSBuZXcgWE1MSHR0cFJlcXVlc3QoKTsKCQlyZXEub25yZWFk
        eXN0YXRlY2hhbmdlID0gZnVuY3Rpb24oKSB7CgkJCWlmIChyZXEucmVhZHlT
        dGF0ZSA9PSA0KSB7CgkJCQlpZiAocmVxLnN0YXR1cyA9PSAyMDApIHsKCQoJ
        CQkJCXJlcS5vbnJlYWR5c3RhdGVjaGFuZ2UgPSBudWxsOwoJCQkJCXZhciBv
        Ymo7CgkJCQkJCgkJCQkJaWYgKHJlcS5yZXNwb25zZVRleHQuaW5kZXhPZign
        eycpID09IDApIHsKCQkJCQkJdHJ5IHsKCQkJCQkJCWV2YWwoJ29iaiA9ICcr
        cmVxLnJlc3BvbnNlVGV4dCk7CgkJCQkJCX0gY2F0Y2ggKGVycikgewoJCQkJ
        CQkJY29uc29sZS53YXJuKCd1bmFibGUgdG8gZG8gYW55dGhpbmcgd2l0aCBz
        aW1wbGVfYWpheF9jYWxsIHJzcCcpOwoJCQkJCQkJY29uc29sZS5lcnJvcihl
        cnIpOwoJCQkJCQl9CgkJCQkJfSBlbHNlIHsKCQkJCQkJb2JqID0gewoJCQkJ
        CQkJb2s6IDEsCgkJCQkJCQlyc3A6IHJlcS5yZXNwb25zZVRleHQKCQkJCQkJ
        fQoJCQkJCX0KCQkJCQlpZiAoaGFuZGxlcikgaGFuZGxlcihvYmopOwoJCQkJ
        fSBlbHNlIHsKCQkJCQloYW5kbGVyKHsKCQkJCQkJJ29rJwk6IDAsCgkJCQkJ
        CSdlcnJvcicJOiAiTm9uLTIwMCBIVFRQIHN0YXR1czogIityZXEuc3RhdHVz
        LAoJCQkJCQknZGVidWcnCTogcmVxLnJlc3BvbnNlVGV4dAoJCQkJCX0pOwoJ
        CQkJfQoJCQl9CgkJfQoJCgkJcmVxLm9wZW4oJ1BPU1QnLCB1cmwsIDEpOwoJ
        CXJlcS5zZXRSZXF1ZXN0SGVhZGVyKCJDb250ZW50LVR5cGUiLCAiYXBwbGlj
        YXRpb24veC13d3ctZm9ybS11cmxlbmNvZGVkIik7CgkKCQl2YXIgb2JqX2Fy
        Z3MyID0gW107CgkJZm9yIChpIGluIG9ial9hcmdzKSB7CgkJCW9ial9hcmdz
        MltvYmpfYXJnczIubGVuZ3RoXSA9IGVuY29kZVVSSUNvbXBvbmVudChpKSsn
        PScrZW5jb2RlVVJJQ29tcG9uZW50KG9ial9hcmdzW2ldKTsKCQl9CgkKCQly
        ZXEuc2VuZChvYmpfYXJnczIuam9pbignJicpKTsKCX0sCgkKCWNhbGxNYWNH
        YXA6IGZ1bmN0aW9uKG1ldGhvZCwgYXJncykgewoJCXZhciBhcmdzX3N0ciA9
        ICcnOwoJCWlmIChhcmdzICE9IHVuZGVmaW5lZCAmJiBhcmdzICE9IG51bGwp
        IHsKCQkJdHJ5IHsKCQkJCWFyZ3Nfc3RyID0gSlNPTi5zdHJpbmdpZnkoYXJn
        cykKCQkJfSBjYXRjaChlKSB7CgkJCQlhcmdzX3N0ciA9ICdiYWQvbm8gYXJn
        cyc7CgkJCX0KCQl9CgkJCgkJY29uc29sZS5pbmZvKFRTTWFrZUxvZ0RhdGUo
        KSsnVFNTU0IgJyttZXRob2QrJyAnK2FyZ3Nfc3RyKTsKCQkKCQlpZiAobWV0
        aG9kID09ICdyZWxvYWQnICYmIG1hY2dhcC5hcHAgJiYgbWFjZ2FwLmFwcC5y
        ZWxvYWQpIHsKCQkJbWFjZ2FwLmFwcC5yZWxvYWQoKTsKCQkJcmV0dXJuIHRy
        dWU7CgkJfQoJCQoJCWlmIChtZXRob2QgPT0gJ2RpZFN0YXJ0TG9hZGluZycg
        JiYgbWFjZ2FwLmFwcCAmJiBtYWNnYXAuYXBwLmRpZFN0YXJ0TG9hZGluZykg
        ewoJCQltYWNnYXAuYXBwLmRpZFN0YXJ0TG9hZGluZyhhcmdzKTsKCQkJcmV0
        dXJuIHRydWU7CgkJfQoJCQoJCWlmIChtZXRob2QgPT0gJ2RpZEZpbmlzaExv
        YWRpbmcnICYmIG1hY2dhcC5hcHAgJiYgbWFjZ2FwLmFwcC5kaWRGaW5pc2hM
        b2FkaW5nKSB7CgkJCW1hY2dhcC5hcHAuZGlkRmluaXNoTG9hZGluZygpOwoJ
        CQlyZXR1cm4gdHJ1ZTsKCQl9CgkJCgkJaWYgKG1ldGhvZCA9PSAnc2V0Q3Vy
        cmVudFRlYW0nICYmIG1hY2dhcC5zdGF0ZSAmJiBtYWNnYXAuc3RhdGUuc2V0
        Q3VycmVudFRlYW0pIHsKCQkJbWFjZ2FwLnN0YXRlLnNldEN1cnJlbnRUZWFt
        KGFyZ3MpOwoJCQlyZXR1cm4gdHJ1ZTsKCQl9CgkJCgkJaWYgKG1ldGhvZCA9
        PSAnZGlzYWJsZVNlY3VyZUlucHV0JyAmJiBtYWNnYXAuYXBwICYmIG1hY2dh
        cC5hcHAuZGlzYWJsZVNlY3VyZUlucHV0KSB7CgkJCW1hY2dhcC5hcHAuZGlz
        YWJsZVNlY3VyZUlucHV0KCk7CgkJCXJldHVybiB0cnVlOwoJCX0KCQkKCQly
        ZXR1cm4gZmFsc2U7Cgl9LAoJCgljYWxsOiBmdW5jdGlvbihtZXRob2QsIG9i
        al9hcmdzLCBhcmdzLCBoYW5kbGVyKSB7CgkJaWYgKHdpbmRvdy5tYWNnYXAp
        IHsKCQkJcmV0dXJuIFRTU1NCLmNhbGxNYWNHYXAobWV0aG9kLCBhcmdzKTsK
        CQl9CgkJCgkJaWYgKHdpbmRvdy5pc193aW5zc2IpIHsKCQkJVFNTU0IuY2Fs
        bENFRjMobWV0aG9kLCBvYmpfYXJncywgaGFuZGxlcik7CgkJCXJldHVybiB0
        cnVlOwoJCX0KCQkKCQlyZXR1cm4gZmFsc2U7Cgl9Cn0KCjwvc2NyaXB0Pjxz
        Y3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij4KCVRTU1NCLmNhbGwoJ2Rp
        ZEZpbmlzaExvYWRpbmcnKTsKPC9zY3JpcHQ+CiAgICA8bWV0YSBjaGFyc2V0
        PSJ1dGYtOCI+CiAgICA8dGl0bGU+VGVzdCBUZWFtIFNsYWNrPC90aXRsZT4K
        ICAgIDxtZXRhIG5hbWU9ImF1dGhvciIgY29udGVudD0iVGlueSBTcGVjayI+
        Cgo8IS0tIG91dHB1dF9jc3MgImNvcmUiIC0tPgogICAgPGxpbmsgaHJlZj0i
        aHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvODgxNi9zdHls
        ZS9saWJzX2pxdWVyeS5tb25rZXlTY3JvbGxfMTM3NjM1ODUyMy5odHRwcy5j
        c3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxp
        bmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQv
        MTcyNTcvc3R5bGUvbGlic19ib290c3RyYXBfMTM5NDU4NzUyOC5odHRwcy5j
        c3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxp
        bmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQv
        NjY4OS9zdHlsZS9saWJzX2ZvbnQtYXdlc29tZV8xMzg3Mzk5MzUyLmh0dHBz
        LmNzcyIgcmVsPSJzdHlsZXNoZWV0IiB0eXBlPSJ0ZXh0L2NzcyI+CiAgICA8
        bGluayBocmVmPSJodHRwczovL3NsYWNrLmdsb2JhbC5zc2wuZmFzdGx5Lm5l
        dC85ODg5L3N0eWxlL2xpYnNfbGFkZGEtdGhlbWVsZXNzXzEzNzg4NTY5OTUu
        aHR0cHMuY3NzIiByZWw9InN0eWxlc2hlZXQiIHR5cGU9InRleHQvY3NzIj4K
        ICAgIDxsaW5rIGhyZWY9Imh0dHBzOi8vc2xhY2suZ2xvYmFsLnNzbC5mYXN0
        bHkubmV0LzE2NTIyL3N0eWxlL3dlYl9sYXlvdXRfMTM5MzYyNjMwMy5odHRw
        cy5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAg
        PGxpbmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5u
        ZXQvMTY5MTcvc3R5bGUvZm9ybXNfMTM5NDEzNDU1NS5odHRwcy5jc3MiIHJl
        bD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxpbmsgaHJl
        Zj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvMTU0MzAv
        c3R5bGUvYnV0dG9uc18xMzkzNjI2Mzc4Lmh0dHBzLmNzcyIgcmVsPSJzdHls
        ZXNoZWV0IiB0eXBlPSJ0ZXh0L2NzcyI+CiAgICA8bGluayBocmVmPSJodHRw
        czovL3NsYWNrLmdsb2JhbC5zc2wuZmFzdGx5Lm5ldC8xNzAxNi9zdHlsZS90
        aXBzXzEzOTQyMjQ4OTkuaHR0cHMuY3NzIiByZWw9InN0eWxlc2hlZXQiIHR5
        cGU9InRleHQvY3NzIj4KICAgIDxsaW5rIGhyZWY9Imh0dHBzOi8vc2xhY2su
        Z2xvYmFsLnNzbC5mYXN0bHkubmV0LzE3NzQ3L3N0eWxlL3R5cG9ncmFwaHlf
        MTM5NTYyMzk3NC5odHRwcy5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0i
        dGV4dC9jc3MiPgogICAgPGxpbmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9i
        YWwuc3NsLmZhc3RseS5uZXQvMTcyNTcvc3R5bGUvdXRpbGl0aWVzXzEzOTQ1
        ODc1MjEuaHR0cHMuY3NzIiByZWw9InN0eWxlc2hlZXQiIHR5cGU9InRleHQv
        Y3NzIj4KICAgIDxsaW5rIGhyZWY9Imh0dHBzOi8vc2xhY2suZ2xvYmFsLnNz
        bC5mYXN0bHkubmV0LzE2MzcwL3N0eWxlL21lbnVfMTM5MzYyNjI3Mi5odHRw
        cy5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAg
        PGxpbmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5u
        ZXQvMTQxNTIvc3R5bGUvYWN0aXZpdHlfMTM5MzYyNjMyMC5odHRwcy5jc3Mi
        IHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxpbmsg
        aHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvMTcy
        OTEvc3R5bGUvY2hhbm5lbHNfMTM5NDY1NzM1MC5odHRwcy5jc3MiIHJlbD0i
        c3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxpbmsgaHJlZj0i
        aHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvMTc3NDcvc3R5
        bGUvbWVzc2FnZXNfMTM5NTYyMzk4MC5odHRwcy5jc3MiIHJlbD0ic3R5bGVz
        aGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxpbmsgaHJlZj0iaHR0cHM6
        Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvMTc2ODIvc3R5bGUvbWVz
        c2FnZXNfZGVuc2VfMTM5NTQyMzMxMC5odHRwcy5jc3MiIHJlbD0ic3R5bGVz
        aGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxpbmsgaHJlZj0iaHR0cHM6
        Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvMTcwNTcvc3R5bGUvbWVz
        c2FnZXNfbGlnaHRfMTM5NDI0MjUzNC5odHRwcy5jc3MiIHJlbD0ic3R5bGVz
        aGVldCIgdHlwZT0idGV4dC9jc3MiPgogICAgPGxpbmsgaHJlZj0iaHR0cHM6
        Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQvMTc0MDUvc3R5bGUvZmls
        ZXNfMTM5NDgzMjQ1My5odHRwcy5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlw
        ZT0idGV4dC9jc3MiPgogICAgPGxpbmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5n
        bG9iYWwuc3NsLmZhc3RseS5uZXQvMTcwNTcvc3R5bGUvbWVtYmVyc18xMzk0
        MjQyNTEyLmh0dHBzLmNzcyIgcmVsPSJzdHlsZXNoZWV0IiB0eXBlPSJ0ZXh0
        L2NzcyI+CiAgICA8bGluayBocmVmPSJodHRwczovL3NsYWNrLmdsb2JhbC5z
        c2wuZmFzdGx5Lm5ldC8xNzMxOC9zdHlsZS9zZWFyY2hfMTM5NDczNDIzMy5o
        dHRwcy5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgog
        ICAgPGxpbmsgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3Rs
        eS5uZXQvMTY1OTkvc3R5bGUvc3RhcnNfMTM5MzcyMDQ2My5odHRwcy5jc3Mi
        IHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgoKPCEtLSBvdXRw
        dXRfY3NzICJyZWd1bGFyIiAtLT4KCgoKCgoKICAgIDwhLS1baWYgbHQgSUUg
        OV0+CiAgICA8c2NyaXB0IHNyYz0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3Ns
        LmZhc3RseS5uZXQvMTI2MS9qcy9saWJzX2h0bWw1c2hpdl8xMzYxOTIzODg2
        Lmh0dHBzLmpzIj48L3NjcmlwdD4KICAgIDwhW2VuZGlmXS0tPgoKICAgIDxs
        aW5rIGhyZWY9J2h0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzP2Zh
        bWlseT1MYXRvOjQwMCw3MDAsOTAwLDQwMGl0YWxpYyw3MDBpdGFsaWMsOTAw
        aXRhbGljJyByZWw9J3N0eWxlc2hlZXQnIHR5cGU9J3RleHQvY3NzJz4KCgo8
        bGluayBpZD0iZmF2aWNvbiIgcmVsPSJzaG9ydGN1dCBpY29uIiBocmVmPSJo
        dHRwczovL3NsYWNrLmdsb2JhbC5zc2wuZmFzdGx5Lm5ldC8xNzI4Mi9pbWcv
        aWNvbnMvZmF2aWNvbi0zMi5wbmciIHNpemVzPSIxNngxNiAzMngzMiA0OHg0
        OCIgdHlwZT0iaW1hZ2UvcG5nIiAvPgoKPGxpbmsgcmVsPSJpY29uIiBocmVm
        PSJodHRwczovL3NsYWNrLmdsb2JhbC5zc2wuZmFzdGx5Lm5ldC85NDI3L2lt
        Zy9pY29ucy9hcHAtMjU2LnBuZyIgc2l6ZXM9IjI1NngyNTYiIHR5cGU9Imlt
        YWdlL3BuZyIgLz4KCjxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVj
        b21wb3NlZCIgc2l6ZXM9IjE1MngxNTIiIGhyZWY9Imh0dHBzOi8vc2xhY2su
        Z2xvYmFsLnNzbC5mYXN0bHkubmV0Lzk3MTIvaW1nL2ljb25zL2lvcy0xNTIu
        cG5nIiAvPgo8bGluayByZWw9ImFwcGxlLXRvdWNoLWljb24tcHJlY29tcG9z
        ZWQiIHNpemVzPSIxNDR4MTQ0IiBocmVmPSJodHRwczovL3NsYWNrLmdsb2Jh
        bC5zc2wuZmFzdGx5Lm5ldC85NDI2L2ltZy9pY29ucy9pb3MtMTQ0LnBuZyIg
        Lz4KPGxpbmsgcmVsPSJhcHBsZS10b3VjaC1pY29uLXByZWNvbXBvc2VkIiBz
        aXplcz0iMTIweDEyMCIgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3Ns
        LmZhc3RseS5uZXQvOTQyNi9pbWcvaWNvbnMvaW9zLTEyMC5wbmciIC8+Cjxs
        aW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgc2l6ZXM9
        IjExNHgxMTQiIGhyZWY9Imh0dHBzOi8vc2xhY2suZ2xvYmFsLnNzbC5mYXN0
        bHkubmV0Lzk0MjYvaW1nL2ljb25zL2lvcy0xMTQucG5nIiAvPgo8bGluayBy
        ZWw9ImFwcGxlLXRvdWNoLWljb24tcHJlY29tcG9zZWQiIHNpemVzPSI3Mng3
        MiIgaHJlZj0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQv
        OTQyNi9pbWcvaWNvbnMvaW9zLTcyLnBuZyIgLz4KPGxpbmsgcmVsPSJhcHBs
        ZS10b3VjaC1pY29uLXByZWNvbXBvc2VkIiBocmVmPSJodHRwczovL3NsYWNr
        Lmdsb2JhbC5zc2wuZmFzdGx5Lm5ldC85NDI2L2ltZy9pY29ucy9pb3MtNTcu
        cG5nIiAvPgoKPG1ldGEgbmFtZT0ibXNhcHBsaWNhdGlvbi1UaWxlQ29sb3Ii
        IGNvbnRlbnQ9IiNGRkZGRkYiIC8+CjxtZXRhIG5hbWU9Im1zYXBwbGljYXRp
        b24tVGlsZUltYWdlIiBjb250ZW50PSJodHRwczovL3NsYWNrLmdsb2JhbC5z
        c2wuZmFzdGx5Lm5ldC85NDI3L2ltZy9pY29ucy9hcHAtMTQ0LnBuZyIgLz48
        c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+CgoJKGZ1bmN0aW9uKGks
        cyxvLGcscixhLG0pe2lbJ0dvb2dsZUFuYWx5dGljc09iamVjdCddPXI7aVty
        XT1pW3JdfHxmdW5jdGlvbigpewoJKGlbcl0ucT1pW3JdLnF8fFtdKS5wdXNo
        KGFyZ3VtZW50cyl9LGlbcl0ubD0xKm5ldyBEYXRlKCk7YT1zLmNyZWF0ZUVs
        ZW1lbnQobyksCgltPXMuZ2V0RWxlbWVudHNCeVRhZ05hbWUobylbMF07YS5h
        c3luYz0xO2Euc3JjPWc7bS5wYXJlbnROb2RlLmluc2VydEJlZm9yZShhLG0p
        Cgl9KSh3aW5kb3csZG9jdW1lbnQsJ3NjcmlwdCcsJy8vd3d3Lmdvb2dsZS1h
        bmFseXRpY3MuY29tL2FuYWx5dGljcy5qcycsJ2dhJyk7CglnYSgnY3JlYXRl
        JywgJ1VBLTEwNjQ1OC0xNycsICdzbGFjay5jb20nKTsKCWdhKCdzZW5kJywg
        J3BhZ2V2aWV3Jyk7CgoJKGZ1bmN0aW9uKGUsYyxiLGYsZCxnLGEpe2UuU2xh
        Y2tCZWFjb25PYmplY3Q9ZDsKCWVbZF09ZVtkXXx8ZnVuY3Rpb24oKXsoZVtk
        XS5xPWVbZF0ucXx8W10pLnB1c2goWzEqbmV3IERhdGUoKSxhcmd1bWVudHNd
        KX07CgllW2RdLmw9MSpuZXcgRGF0ZSgpO2c9Yy5jcmVhdGVFbGVtZW50KGIp
        O2E9Yy5nZXRFbGVtZW50c0J5VGFnTmFtZShiKVswXTsKCWcuYXN5bmM9MTtn
        LnNyYz1mO2EucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUoZyxhKQoJfSkod2lu
        ZG93LGRvY3VtZW50LCJzY3JpcHQiLCJodHRwczovL3NsYWNrLmdsb2JhbC5z
        c2wuZmFzdGx5Lm5ldC8xNTg5OS9qcy9saWJzX2JlYWNvbl8xMzkyNDQ0OTEy
        Lmh0dHBzLmpzIiwic2IiKTsKCXNiKCdzZXQnLCAndG9rZW4nLCAnMzMwN2Y0
        MzY5NjNlMDJkNGY5ZWI4NWNlNTE1OTc0NGMnKTsKCXNiKCd0cmFjaycsICdw
        YWdldmlldycpOwoKCglmdW5jdGlvbiB0cmFjayhhKXtnYSgnc2VuZCcsJ2V2
        ZW50Jywnd2ViJyxhKTtzYigndHJhY2snLGEpO30KCjwvc2NyaXB0PgogIDwv
        aGVhZD4KCiAgPGJvZHkgb25kcmFnb3Zlcj0icmV0dXJuIGZhbHNlIiBjbGFz
        cz0icGFkZGVkIj4KCgkJCQoJCgk8ZGl2IGlkPSJzbGFja19oZWFkZXIiPgoJ
        CTxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CgoJCQk8ZGl2IHN0eWxlPSJmbG9h
        dDogcmlnaHQ7IG1hcmdpbi10b3A6IC0zMnB4Ij4KCQkJCQkJPGEgaHJlZj0i
        aHR0cHM6Ly9zbGFjay5jb20vc2lnbmluIiBjbGFzcz0iYnRuIGJ0bi1vdXRs
        aW5lIj5TaWduIGluPC9hPgoJCQkJPC9kaXY+CgoJCQk8YSBocmVmPSIvIj48
        aW1nIHNyYz0iaHR0cHM6Ly9zbGFjay5nbG9iYWwuc3NsLmZhc3RseS5uZXQv
        ODkxMS9pbWcvc2xhY2tfbG9nby5wbmciIHN0eWxlPSJ3aWR0aDogMTgwcHg7
        IGhlaWdodDogNjlweDsgbWFyZ2luLWxlZnQ6IC0zcmVtIiAvPjwvYT4KCQkJ
        PGhyIC8+CgkJPC9kaXY+Cgk8L2Rpdj4KCQkJCgkJCgkKPGRpdiBjbGFzcz0i
        Y29udGFpbmVyIj4KCgk8aDE+U2lnbiBpbiB0byBUZXN0IFRlYW08L2gxPgoK
        CQoJCQkJCQoKCTxmb3JtIGFjdGlvbj0iLyIgbWV0aG9kPSJwb3N0IiBhY2Nl
        cHQtZW5jb2Rpbmc9IlVURi04Ij4KCQk8aW5wdXQgdHlwZT0iaGlkZGVuIiBu
        YW1lPSJzaWduaW4iIHZhbHVlPSIxIiAvPgoJCTxpbnB1dCB0eXBlPSJoaWRk
        ZW4iIG5hbWU9InJlZGlyIiB2YWx1ZT0iIiAvPgoJCTxpbnB1dCB0eXBlPSJo
        aWRkZW4iIG5hbWU9ImNydW1iIiB2YWx1ZT0iMTM5NTY3NTc2Ny0yODVhNjMx
        MGJhLeKYgyIgLz4KCgkJPHAgY2xhc3M9ImNvbnRyb2wtZ3JvdXAgIj4KCQkJ
        PGxhYmVsIGNsYXNzPSJjb250cm9sLWxhYmVsIiBmb3I9ImVtYWlsIj5FbWFp
        bCBBZGRyZXNzPC9sYWJlbD4KCQkJPGlucHV0IHR5cGU9ImVtYWlsIiBuYW1l
        PSJlbWFpbCIgc2l6ZT0iNDAiIHZhbHVlPSIiIC8+CgkJPC9wPgoKCQk8cCBj
        bGFzcz0iY29udHJvbC1ncm91cCAiPgoJCQk8bGFiZWwgY2xhc3M9ImNvbnRy
        b2wtbGFiZWwiIGZvcj0icGFzc3dvcmQiPlBhc3N3b3JkPC9sYWJlbD4KCQkJ
        PGlucHV0IHR5cGU9InBhc3N3b3JkIiBuYW1lPSJwYXNzd29yZCIgc2l6ZT0i
        NDAiIC8+CgkJCTxzcGFuIGNsYXNzPSJpbnB1dF9ub3RlIGluZGVudGVkIj4K
        CQkJCTxsYWJlbCBjbGFzcz0iY2hlY2tib3giPjxpbnB1dCB0eXBlPSJjaGVj
        a2JveCIgbmFtZT0icmVtZW1iZXIiIGNoZWNrZWQgLz4gUmVtZW1iZXIgbWUg
        b24gdGhpcyBjb21wdXRlcjwvbGFiZWw+PGJyIC8+CgkJCQk8YSBocmVmPSIv
        Zm9yZ290Ij5Gb3Jnb3R0ZW4geW91ciBwYXNzd29yZD88L2E+CgkJCTwvc3Bh
        bj4KCQk8L3A+CgoJCTxwIGNsYXNzPSJpbmRlbnRlZCI+PGlucHV0IHR5cGU9
        InN1Ym1pdCIgY2xhc3M9ImJ0biBidG4tcHJpbWFyeSIgdmFsdWU9IlNpZ24g
        SW4iIC8+PC9wPgoJCQkKCTwvZm9ybT4KCgkKCTxociAvPgoKCTxwIGNsYXNz
        PSJtaW5pIj5UbyBzdGFydCB1c2luZyBTbGFjaywgeW91J2xsIG5lZWQgdG8g
        YmUgaW52aXRlZCBieSB5b3VyIHRlYW0gYWRtaW5pc3RyYXRvci48L3A+Cgo8
        L2Rpdj4KCgk8ZGl2IGNsYXNzPSJjbGVhci1ib3RoIj48L2Rpdj4KCjxkaXYg
        aWQ9ImZvb3RlciI+CQkKCTxzcGFuIGNsYXNzPSJmbG9hdC1yaWdodCI+CgkJ
        CQk8YSBocmVmPSJodHRwczovL2FwaS5zbGFjay5jb20vIj5BUEk8L2E+CgkJ
        PGEgaHJlZj0iL3ByaWNpbmciPlByaWNpbmc8L2E+CQkJCQoJCTxhIGhyZWY9
        Ii90ZXJtcy1vZi1zZXJ2aWNlIj5UZXJtcyBvZiBTZXJ2aWNlPC9hPgoJCTxh
        IGhyZWY9Ii9wcml2YWN5LXBvbGljeSI+UHJpdmFjeSBQb2xpY3k8L2E+CgkJ
        PGEgaHJlZj0iL3NlY3VyaXR5Ij5TZWN1cml0eTwvYT4KCQk8YSBocmVmPSIv
        aGVscC9jb250YWN0Ij5Db250YWN0PC9hPgoJCTxhIGhyZWY9Imh0dHA6Ly93
        d3cudGlueXNwZWNrLmNvbSI+VGlueSBTcGVjaywgSW5jPC9hPgoJPC9zcGFu
        Pgo8L2Rpdj4KCgoKCgo8IS0tIG91dHB1dF9qcyAiY29yZSIgLS0+CjxzY3Jp
        cHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Imh0dHBzOi8vc2xhY2su
        Z2xvYmFsLnNzbC5mYXN0bHkubmV0Lzk5NDkvanMvbGlic19qcXVlcnktMS44
        LjJfMTM3OTAxMTU4Ny5odHRwcy5qcyIgY3Jvc3NvcmlnaW49ImFub255bW91
        cyI+PC9zY3JpcHQ+CjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBz
        cmM9Imh0dHBzOi8vc2xhY2suZ2xvYmFsLnNzbC5mYXN0bHkubmV0LzEwODYw
        L2pzL2xpYnNfZmxhc2hfZGV0ZWN0XzEzODExNjcyMTYuaHR0cHMuanMiIGNy
        b3Nzb3JpZ2luPSJhbm9ueW1vdXMiPjwvc2NyaXB0Pgo8c2NyaXB0IHR5cGU9
        InRleHQvamF2YXNjcmlwdCIgc3JjPSJodHRwczovL3NsYWNrLmdsb2JhbC5z
        c2wuZmFzdGx5Lm5ldC8xNTg0MS9qcy9saWJzX2Jvb3RzdHJhcF8xMzkyNDAz
        NjI0Lmh0dHBzLmpzIiBjcm9zc29yaWdpbj0iYW5vbnltb3VzIj48L3Njcmlw
        dD4KCjwhLS0gb3V0cHV0X2pzICJzZWNvbmRhcnkiIC0tPgoKPCEtLSBvdXRw
        dXRfanMgInJlZ3VsYXIiIC0tPgoKCgoKPCEtLSBzbGFjay13d3cyMDggLyAy
        MDE0LTAzLTI0IDA4OjQyOjQ3IC8gdjE3NzUyIC0tPgoKPC9ib2R5Pgo8L2h0
        bWw+
    http_version: 
  recorded_at: Mon, 24 Mar 2014 15:42:50 GMT
recorded_with: VCR 2.8.0
